### PR TITLE
PCF-126 make an app for v1

### PR DESCRIPTION
**Pull request by Aisha-D**
PR for DNAnexus app. The rmarkdown is not added in this PR and will be added in for the next PR.

Example of the app running: https://platform.dnanexus.com/projects/GQ0yQk040f92Z2gJk5Y535zq/monitor/job/GXB6KVj40f9Pq12ZgZZ8bq0k

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Aisha-D)

___
*[`src/eggd_pancan_report_generator.sh` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o8mCUDlyuQJl-a5bG:-N_o8mCUDlyuQJl-a5bH:b49ahe8) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L31)):*
> ```Shell
>     sed -e 's/chr21/21/' | sed -e 's/chr22/22/' | \
>     sed -e 's/chrX/X/' | sed -e 's/chrY/Y/' | \
>     sed -e 's/chrM/M/' | samtools reheader - $bam_name > ${bam_prefix}.nochr.bam
> ```

I find it easier with long piped commands to format with the pipe dropped to a new line:
```
 samtools view -H $bam_name \
    | sed -e 's/chr1/1/' | sed -e 's/chr2/2/' \
    | sed -e 's/chr3/3/' | sed -e 's/chr4/4/'
```

also, why so many `sed`s? wy not just a single chr drop from the whole header? I've an example somewhere I can dig out with awk I think



_Code quote:_
```Shell
    samtools view -H $bam_name |\
    sed -e 's/chr1/1/' | sed -e 's/chr2/2/' | \
    sed -e 's/chr3/3/' | sed -e 's/chr4/4/' | \
    sed -e 's/chr5/5/' | sed -e 's/chr6/6/' | \
    sed -e 's/chr7/7/' | sed -e 's/chr8/8/' | \
    sed -e 's/chr9/9/' | sed -e 's/chr10/10/' | \
    sed -e 's/chr11/11/' | sed -e 's/chr12/12/' | \
    sed -e 's/chr13/13/' | sed -e 's/chr14/14/' | \
    sed -e 's/chr15/15/' | sed -e 's/chr16/16/' | \
    sed -e 's/chr17/17/' | sed -e 's/chr18/18/' | \
    sed -e 's/chr19/19/' | sed -e 's/chr20/20/' | \
    sed -e 's/chr21/21/' | sed -e 's/chr22/22/' | \
    sed -e 's/chrX/X/' | sed -e 's/chrY/Y/' | \
    sed -e 's/chrM/M/' | samtools reheader - $bam_name > ${bam_prefix}.nochr.bam
```
___
*[`src/eggd_pancan_report_generator.sh` line 39 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o9NaIAezTWs5PcFpA:-N_o9NaIAezTWs5PcFpB:burpnwz) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L39)):*
> ```Shell
>     CHI_IMAGE_ID=$(sudo docker images --format="{{.Repository}} {{.ID}}" | grep "^sample_report" | cut -d' ' -f2)
> 
>     # get" the Rscript with the paths in
> ```

cheeky bonus quote



_Code quote:_
```Shell
"
```
___
*[`src/eggd_pancan_report_generator.sh` line 53 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o9ZJ054jJMgfjMMva:-N_o9ZJ054jJMgfjMMvb:b-58so6z) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L53)):*
> ```Shell
> 
> 
>     docker run -v /home/dnanexus:/home/software $CHI_IMAGE_ID /bin/bash -c 'ls; cat cmd.sh; bash cmd.sh'
> ```

needed?



_Code quote:_
```Shell
ls; cat cmd.sh; 
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`src/eggd_pancan_report_generator.sh` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o8mCUDlyuQJl-a5bG:-N_riVTb2bSbT-m7bykS:bwb9ybj) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L31)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I find it easier with long piped commands to format with the pipe dropped to a new line:
```
 samtools view -H $bam_name \
    | sed -e 's/chr1/1/' | sed -e 's/chr2/2/' \
    | sed -e 's/chr3/3/' | sed -e 's/chr4/4/'
```

also, why so many `sed`s? wy not just a single chr drop from the whole header? I've an example somewhere I can dig out with awk I think
</blockquote></details>

Done.
Did you also find the easier method?
___
*[`src/eggd_pancan_report_generator.sh` line 39 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o9NaIAezTWs5PcFpA:-N_riH043Pcoln4X3tgC:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L39)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

cheeky bonus quote
</blockquote></details>

Done.
___
*[`src/eggd_pancan_report_generator.sh` line 53 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o9ZJ054jJMgfjMMva:-N_ri_aN4oz17itXcHh4:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L53)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/eggd_pancan_report_generator.sh` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o8mCUDlyuQJl-a5bG:-N_s59xHDtQ7OsvMwqFR:bhm4gme) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L31)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Done.
Did you also find the easier method?
</blockquote></details>

ahh no I remember, I did this with bcftools here: https://github.com/eastgenomics/eggd_vcf_rescue/blob/08dcf29a41990cfbaf1f12f7409c4c5efd70daa2/src/eggd_vcf_rescue.sh#L158

including this mapping file in the repo here: https://github.com/eastgenomics/eggd_vcf_rescue/blob/main/resources/home/dnanexus/chr_prefix_map.txt

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`src/eggd_pancan_report_generator.sh` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o8mCUDlyuQJl-a5bG:-N_sWbl14q4Jt2US70DU:b-cp4bky) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L31)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

ahh no I remember, I did this with bcftools here: https://github.com/eastgenomics/eggd_vcf_rescue/blob/08dcf29a41990cfbaf1f12f7409c4c5efd70daa2/src/eggd_vcf_rescue.sh#L158

including this mapping file in the repo here: https://github.com/eastgenomics/eggd_vcf_rescue/blob/main/resources/home/dnanexus/chr_prefix_map.txt
</blockquote></details>

bcftools only supports vcfs doesnt it?



_Code snippet:_
```Shell
~$ bcftools annotate -h
annotate: option requires an argument -- 'h'

About:   Annotate and edit VCF/BCF files.
Usage:   bcftools annotate [options] <in.vcf.gz>
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/eggd_pancan_report_generator.sh` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o8mCUDlyuQJl-a5bG:-N_sZYetDaJjetsfjlJp:btpo98o) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L31)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

bcftools only supports vcfs doesnt it?
</blockquote></details>

oh I am blind :facepalm: 

there is this, but I am happy if you want to stick with your mega-sed: https://www.biostars.org/p/13462/#13463

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`src/eggd_pancan_report_generator.sh` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1#-N_o8mCUDlyuQJl-a5bG:-N_saM0bEaI2WQg_mAyQ:bm3zkxs) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/2c51424b7d5a7bb972ed006427808aba354f367d/src/eggd_pancan_report_generator.sh#L31)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

oh I am blind :facepalm: 

there is this, but I am happy if you want to stick with your mega-sed: https://www.biostars.org/p/13462/#13463
</blockquote></details>

i used regex

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
